### ISSUE TITLE
Countdown: how to change startValues when Timer is already initialized

### ISSUE THREAD

**Issue by koba-1** [albert-gonzalez/easytimer.js#102]
Hello, how can I change the countdown, for example, from 10 to 55 seconds if the Timer is already initialized? This is my init, and by default I pass only the countdown parameter:

`timer = new easytimer.Timer({ countdown: true });`
`timer.start({ startValues:{seconds: 10}});`

When I try to reset and start again passing 55 seconds, my value is ignored and the countdown restarts from 10:

`timer.start({ startValues: {seconds: 55} });`

I prepared a fiddle: https://jsfiddle.net/Lhjv6ym0/

Thank you very much.

**Comment by koba-1** [comment]
I checked your code, the "problem" is that if the Timer is already started, the second start method will be ignored:

`if (isRunning()) {
        return;
      }`

 I think it isn't much intuitive... maybe it could be better with a specific Init method that replace the old config and stops the Timer? Just a suggestion.
Thank you for this useful lib :)

**Comment by koba-1** [comment]
Anyway, this is how I made the countdown work: https://jsfiddle.net/bpx4y76t/

**Comment by albert-gonzalez** [comment]
Hi koba!

glad to see that you resolved the issue. You are right, some methods are not very intuitive... Maybe I'll work on it in the future.

Best regards!

**Comment by satyasaadhak** [comment]
> Anyway, this is how I made the countdown work: https://jsfiddle.net/bpx4y76t/
> 
> Just replace **reset** with **stop** method, than run again with the new config:
> 
> `timer.stop();`
> `timer.start({ startValues:{seconds: 55}});`

I tried just the same thing, isn't working for me. Neither does the timer restart, nor is there any error in the console.
