### ISSUE TITLE
trigger an event only once

### ISSUE THREAD

**Issue by luwol03** [albert-gonzalez/easytimer.js#103]
Hello,

is ther an option or workaround to trigger an event only once?

**Comment by albert-gonzalez** [comment]
Hi,

no, events will be triggered always. If you want to listen to an event only once, you can add a listener, and in the callback remove this listener. For example:

```
timer.addEventListener('secondsUpdated', function myCallback(e) {
    // some actions
    timer.removeEventListener('secondsUpdated', myCallback);
});
```

Best regards!

**Comment by luwol03** [comment]
Ok, that sounds good.. thank you
