### ISSUE TITLE
countdown does not run to zero

### ISSUE THREAD

**Issue by luwol03** [albert-gonzalez/easytimer.js#104]
Hello,

I think I found a bug. I have published the code on [codepen](https://codepen.io/luwol03/pen/bGEmZOj) that can be used to reproduce the problem. I also recorded a video about the problem and uploaded it to [youtube](https://youtu.be/aFgBjQIG5Cg). 

You can see that the timer starts the first couple of runs at a second less than specified and waits for a second until zero runs and then the coundown starts again (that's what I actually want) but after a few times the countdown starts from the specified one seconds and does not run to zero but stops at one and the next countdown starts again.

I hope you understand what I mean.

Best rengards.

**Comment by albert-gonzalez** [comment]
Hi!

I think the problem is here:

```js
timer.on('targetAchieved', function() {
    secondsUpdate({ detail: { timer: timer2 }}); // this line
    
    timer2.start({
      countdown: true,
      startValues: { seconds: 7 },
    });
  });
  
  timer2.on('targetAchieved', function() {
    secondsUpdate({ detail: { timer: timer }}); // this line

    timer.start({
      countdown: true,
      startValues: { seconds: 10 },
    });
  });
```

In the commented lines you are setting the timer value, and this removes instantly the 00:00:00. If you remove these lines, I think it will work as you expect.

I hope this solves your problem.

Best regards!

**Comment by luwol03** [comment]
Yes you are right!  that was the problem!  I `m so stupid.  I'm sorry for creating this issue.

Best regards and thank you very much.

**Comment by albert-gonzalez** [comment]
You are not stupid, we all make mistakes :)

Glad that I could help.

Best regards!
