### ISSUE TITLE
Error starting countdown timer

### ISSUE THREAD

**Issue by goatofanerd** [albert-gonzalez/easytimer.js#105]
`timer.start({countdown: true, startValues: {seconds: time}});`
This for some reason starts a timer of (time * 10), for example, if time is 5, then it sets a timer for 50 seconds. How do I fix this?

**Comment by albert-gonzalez** [comment]
Hi!

it should work correctly. Make sure that you are getting the seconds property and not the secondTenths.

Here you have a working example with some console.logs: https://runkit.com/albert-gonzalez/5ee13501361832001a7c53f7

Best regards!!
