### ISSUE TITLE
Timer fires all 'Chronometer' methods on WP AJAX call

### ISSUE THREAD

**Issue by pkavanaghjr** [albert-gonzalez/easytimer.js#107]
I'm using EasyTimer and it's been working great, but I'm running into an odd issue that I can't seem to pin down.

In my WordPress install, I've got a countdown timer running. When I make an AJAX call it fires all the Chronometer methods in order: 
1. Start
2. Pause
3. Stop
4. Reset

Even though the only call to the timer object I make is "pause()"

I have added event listeners that trigger alert()'s to see this event order happen. I am at a loss for why this is happening as there are zero calls for stop() and reset() in the entire project. 

Any and all help is appreciated, please advise. Thank you!

**Comment by pkavanaghjr** [comment]
As a workaround, i'm trying to add a preventDefault() to the reset event. but it appears that the standard "e.preventDefault()" is not supported. 

```
global.timer_countdown.addEventListener('reset', function (e) {
    e.preventDefault();
});

// error: Uncaught TypeError: e.preventDefault is not a function
```

Please advise, thank you!

**Comment by albert-gonzalez** [comment]
Hi!

Sorry for the late response. The behaviour that you explain is weird. Which version are you using? Could you send me an example of code?

Best regards!

**Comment by albert-gonzalez** [comment]
I close this issue for now. If you have more info, please reopen :)
