### ISSUE TITLE
Uncaught TypeError: customCallback is not a function at easytimer.js:273

### ISSUE THREAD

**Issue by 91Abdullah** [albert-gonzalez/easytimer.js#11]
As soon as I call myTimer.start() console get flooded with subjected message I tried to disabled customCallback at line# 273 to avoid errors but timer isn't getting any values just displaying "NaN"

**Comment by albert-gonzalez** [comment]
Hi!

Can you show me an example of the code that is causing the error?

Thanks!

**Comment by 91Abdullah** [comment]
Actually I'm calling myTime.start() at my ajax success method prior that I'm instantiating all timers. Here's the all code:

function initializeTimers() {
    readyTime = new Timer();
    notReadyTime = new Timer();
    loginTime = new Timer();
    callTime = new Timer();
    wrapupTime = new Timer();
    holdTime = new Timer();
    answeredTime = new Timer();
    talkTime = new Timer();
}

function ajaxPause(reason) {
    $.ajax({
        url: url + "/pause/" + user.id,
        method: 'POST',
        dataType: 'JSON',
        data: {
           reason: reason
        },
        success: function(result, status, xhr) {
            notReadySuccess();
        },
        error: function(xhr, status, error) {
            notReadyFailed(error);
            console.log(error);
        }
    });
}

function notReadySuccess() {
    statusReady = false;
    readyTime.pause();
    notReadyTime.start();
    stopLoading();
    successToast("Success", "State has been changed to Not Ready.");
    $('#ready').attr('disabled', false);
    $('#notReady').attr('disabled', true);
    $('#phoneStatus').html("Not Ready");
}

**Comment by albert-gonzalez** [comment]
Hi!

I have just tested your code in Chrome, Firefox and Safari and it works fine. I changed some lines but the idea of the timers is the same:
```js
function initializeTimers() {
    readyTime = new Timer();
    notReadyTime = new Timer();
    loginTime = new Timer();
    callTime = new Timer();
    wrapupTime = new Timer();
    holdTime = new Timer();
    answeredTime = new Timer();
    talkTime = new Timer();
}

function ajaxPause(reason) {
    setTimeout(function () {
        notReadySuccess();
    }, 1000);
}

function notReadySuccess() {
    statusReady = false;
    readyTime.pause();
    notReadyTime.start();

    notReadyTime.addEventListener('secondsUpdated', function (e) {
        console.log(notReadyTime.getTimeValues().toString());
    });
}

initializeTimers();
ajaxPause();
```

I don't know why your code is failing. Which browser are you using? Which version of easytimer are you using? Copy and paste here the line of your package.json where the library dependency is defined.

Thank you!

**Comment by 91Abdullah** [comment]
Actually this is a Laravel project and I'm developing a Webrtc softphone so I need to show some timers I'm using google chrome and latest version of easytimer.js. Shall I chek with master repo?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by albert-gonzalez** [comment]
The latest published version and the latest commit of master branch are the same.

Are you using npm? Make sure you are using this repo and not some fork that is published in npm too.

Install the lib this way:

`npm install easytimer.js`
