### ISSUE TITLE
CONGRATULATIONS on such an AMAZING project!!!

### ISSUE THREAD

**Issue by inglesuniversal** [albert-gonzalez/easytimer.js#111]
If I were a Movie Critic...   I'd give you TWO THUMBS UP and... 

I would write a quote like this....

     "easytimer.js   ----->   Precision Swiss Watch for your App"  ~    Hugo Barbosa / MyCloudVIP

**Comment by albert-gonzalez** [comment]
You make me laugh! Thank you!
