### ISSUE TITLE
Run countdown timers in a loop

### ISSUE THREAD

**Issue by markahenshaw** [albert-gonzalez/easytimer.js#112]
I am trying to run a series of countdown timers in a loop. How can i hold the loop from cycling to the next until the current countdown has reached its target of 0?

I do an ajax call to get all the timer durations then call
for (i in ajaxData.blindsData){
    $('#level').html(ajaxData.blindsData[i].level_type+" "+ajaxData.blindsData[i].level);
    levelTimer(ajaxData.blindsData[i].level_duration);
  };
which calls
function levelTimer(i,x,y) {
  var countdownTimer = new easytimer.Timer();
  countdownTimer.start({countdown: true, startValues: [0,0,i,0,0]});

  $('#timer').html(countdownTimer.getTimeValues().toString(['minutes','seconds']));

  countdownTimer.addEventListener('secondsUpdated', function (e) {
      $('#timer').html(countdownTimer.getTimeValues().toString(['minutes','seconds']));
      if(countdownTimer.getTimeValues().toString() == "00:01:00"){
        speechSynthesis.speak(new SpeechSynthesisUtterance("Attention! Attention! Blinds will go up in 1 minute! Blinds will be x and y."));
      };
  });

  countdownTimer.addEventListener('minutesUpdated', function (e) {
      
  });

  countdownTimer.addEventListener('targetAchieved', function (e) {
      $('#level').html('KABOOM!!');
  });
};

**Comment by albert-gonzalez** [comment]
Hi! 

I wrote a simple example with a possible solution to your problem. Check it out: https://runkit.com/albert-gonzalez/5fb6a9b28000e70013411da6

I hope it helps!
