### ISSUE TITLE
Negative starting value results in secondTenths reported as "10" instead of "0" while < 0

### ISSUE THREAD

**Issue by nk9** [albert-gonzalez/easytimer.js#114]
Thanks for the useful tool! It's made creating a basic timer _much_ simpler than it would have been.

I'm using a coundown-countup timer, so it will wrap around. I can successfully start it with a negative value, and almost everything works, except secondTenths.

```js
var timer = new easytimer.Timer({
	precision: 'secondTenths',
	startValues: {
		seconds: -10
	}
});
timer.addEventListener('secondTenthsUpdated', secondTenthsUpdated);
timer.start();

function secondTenthsUpdated() {
	let time = timer.getTimeValues().toString(units=['hours', 'minutes', 'seconds', 'secondTenths']);

	console.log(time);
}
```

This results in:

```
script.js:83 00:00:09:9
script.js:83 00:00:09:8
script.js:83 00:00:09:7
script.js:83 00:00:09:6
script.js:83 00:00:09:5
script.js:83 00:00:09:4
script.js:83 00:00:09:3
script.js:83 00:00:09:2
script.js:83 00:00:09:1
script.js:83 00:00:09:10 <==== should be 0
script.js:83 00:00:08:9
```

This only happens when the timer is negative. As soon as it wraps into positive times, the `secondTenths` display 0 as expected.

**Comment by albert-gonzalez** [comment]
Hi!

Thank you for reporting this issue. 

I have just updated the library fixing it. If you get the new version (4.3.2) it should work as expected now.

Best regards!
