### ISSUE TITLE
Start, Pause, Stop and Reset (Chronometer) example

### ISSUE THREAD

**Issue by bekadigital** [albert-gonzalez/easytimer.js#116]
Hello,

In your "Start, Pause, Stop and Reset (Chronometer)" example, it is impossible or I cannot find the solution to program the stop button with a reset of the stopwatch.

Example: click on the stop button, but at the same time reset the count to zero

Thanks for your help.

**Comment by albert-gonzalez** [comment]
Hi!

the stop button resets the easytimer instance, if you click again the start button, the timer will start again from 00:00:00. If you want to show 00:00:00 just after click the stop button, you can do something like this:

```js
timer.addEventListener('stopped', function (e) {
    $('#chronoExample .values').html(timer.getTimeValues().toString());
});
```
