### ISSUE TITLE
display issue of secondTenths

### ISSUE THREAD

**Issue by gazsi51** [albert-gonzalez/easytimer.js#117]
Hello,
I would like to report a minor cosmetic issue displaying the secondTenths. The separator between the second and secondTenths is colon. It would better to use decimal point. Recently it looks like **00:00:00:0**. It should be **00:00:00.0**
Would you please advice how to change the code displaying decimal point between the second and secondTenths value?
Anyway, thanks for this great script.

**Comment by albert-gonzalez** [comment]
Hi!

The toString method is very simple and it doesn't allow diferent separators. If you need a custom format, you can write a method to do that. For example:

```js
const timer = Timer();

timer.start({ precision: 'secondTenths' });

const formatValues = (timeValues) => `${timeValues.toString()}.${timeValues.secondTenths}`;
timer.on('secondTenthsUpdated', () => console.log(formatValues(timer.getTimeValues())));
```

Best regards!

**Comment by gazsi51** [comment]
Hi,
Thank you for the quick answer. I tried it but it does not work. Where to insert your suggested codes. Here is my original codes

`<script src="js/easytimer.min.js"></script>
    <div id="ElapsedTime">
      <p><B>Elapsed time: </B></p>
        <div class="values">00:00:00.0</div>
    	<br>
		<button class="startButton" id="Submit" style="margin-bottom: 10px">Submit</button>
	</div>
   
<script>
var timer = new Timer();
$('#ElapsedTime .startButton').click(function () {
    $("#ajax_stat_result").css({"display":"none"});
    timer.start({precision: 'secondTenths'});
});

timer.addEventListener('secondTenthsUpdated', function (e) {
    $('#ElapsedTime .values').html(timer.getTimeValues().toString(['hours','minutes', 'seconds', 'secondTenths']));
});
</script>`

**Comment by albert-gonzalez** [comment]
Hi again!

No problem. Try to replace your event listener with this:

```js
timer.addEventListener('secondTenthsUpdated', function (e) {
    var timeValues = timer.getTimeValues();
    $('#ElapsedTime .values').html(timeValues.toString(['hours','minutes', 'seconds']) + '.' + timeValues.secondTenths);
});
``` 

This should work.

Best regards!

**Comment by gazsi51** [comment]
Thank you so much. It works very well, as I expected. I appreciate your help very much. I am not a professional coder but fortunately there good guys from this industry like you. TNX..

**Comment by albert-gonzalez** [comment]
You are welcome! Glad to help you.

Best regards!
