### ISSUE TITLE
Set timer values

### ISSUE THREAD

**Issue by SFkCeBo** [albert-gonzalez/easytimer.js#119]
Buenos dias Albert, 

Estoy intentando utilizar tu libreria para poder generar un contador, este contador tambien tiene que cargar los valores almacenados en el caso que estubieran.

No consigo entender como hacerlo, podrias ayudarme?

Gracias

![imagen](https://user-images.githubusercontent.com/38246403/112139424-08630700-8bd3-11eb-832d-fdedb5d2aa1f.png)

**Comment by albert-gonzalez** [comment]
¡Hola!

Timer es una clase que hay que instanciar. Una forma sencilla es utilizar useState, y que el Timer cambie el estado cada vez que se actualice usando un listener. Tienes varios ejemplos de como usar el timer en la página de ejemplos: http://albert-gonzalez.github.io/easytimer.js/

Otra forma es usar el hook de React que publiqué hace unos pocos días. Este hook devuelve una instancia del timer ya preparada, y además actualizará el componente en el que lo uses cada vez que se actualice. Aquí tienes el enlace al repositorio del hook y otro a una página de ejemplo.

https://github.com/albert-gonzalez/easytimer-react-hook
https://albert-gonzalez.github.io/easytimer-react-hook/

¡Saludos!

**Comment by SFkCeBo** [comment]
Solucionado Albert, muchismas gracias por todo!

**Comment by albert-gonzalez** [comment]
¡De nada! Un placer ayudarte
