### ISSUE TITLE
Can't get easytimer load

### ISSUE THREAD

**Issue by scdigitalmedia** [albert-gonzalez/easytimer.js#120]
I've tried every which way to load this file into my app and I can't for the life of me get it loaded. I keep getting:

Timer is not defined 

I've placed this after jquery loads, and before I call the the timer. I've made sure the path is correct and everything.
<script src="easytimer.min.js"></script>
<script>
    var timerInstance = new easytimer.Timer();
</script>

I call and start the timer with 

var timer = new Timer();
timer.start();

I can only get, what looks to be an older version of easytimer to work, however the Reset method call keeps throwing a "reset is not defined" error.

Am I missing anything here? 

`
<script src="../admin/assets/js/jquery.min.js"></script>
<script src="../admin/assets/plugins/easytimer/easytimer.js"></script>
<script>
    var timerInstance = new easytimer.Timer();
</script>

<div id="basicUsage">00:00:00</div>

<script>
    var timer = new Timer();
    timer.start();

    timer.addEventListener('secondsUpdated', function(e) {
        $('#basicUsage').html(timer.getTimeValues().toString());
    });
</script>
`

**Comment by scdigitalmedia** [comment]
var timer = new Timer()

needed to be

var timer = new easytimer.Timer()


I was going by this code example:

var timer = new Timer();
timer.start();

timer.addEventListener('secondsUpdated', function (e) {
    $('#basicUsage').html(timer.getTimeValues().toString());
});

**Comment by albert-gonzalez** [comment]
Hi!

Did you solve it then? If you load the timer using a script tag, you need to call it this way:

```js
  var timerInstance = new easytimer.Timer();
```

Best regards!

**Comment by scdigitalmedia** [comment]
I did. Thank you. I see now where I misread. Your module works great. Appreciate the work you've put into it.

**Comment by albert-gonzalez** [comment]
You are welcome! I close the issue then.

Best regards!
