### ISSUE TITLE
Uncasted startValue yields incorrect timings

### ISSUE THREAD

**Issue by mackieee** [albert-gonzalez/easytimer.js#124]
Love the library! Consice and reliable, so thank you Albert for creating this :)

The only hiccup I had encountered when working with this, was collecting a `startValue` from the DOM. As I was using PHP to dictate this: 

``` html
<div id="countdown-data" data-fromseconds="3000" />
<div id="my-countdown">
    <div class="values"></div>
</div>

<script type="text/javascript">
var myTimer = new easytimer.Timer();
myTimer.start({ 
	countdown: true,
	startValues: { 
		seconds: $('#countdown-data').attr( "data-fromseconds" ))
	}
});

// This results in: 8:20:00, 8 hours & 20 minutes for 3000 seconds - rather than 50 minutes.
$('#my-countdown .values', document).html( myTimer.getTimeValues().toString() );
</script>
```

By casting the string result to int (by means of `parseInt()`), I get the expected 50 minutes. 

``` js
startValues: { 
    seconds: parseInt( $('#countdown-data').attr( "data-fromseconds" )))
}
``` 

I just felt to mention it would be good to either cast the result, or type-check and warn when a string is passed to `startValues`.

**Comment by albert-gonzalez** [comment]
Hi!

Thank you for opening the issue.

You are right, it would be nice to cast these values to integer. I will release a new version with this change :).

Best regards!

**Comment by albert-gonzalez** [comment]
Hi again!

v4.4.0 is published with the change you requested. Now you can pass a string without any problem :)

Best regards!.
