### ISSUE TITLE
Time slowing down when unfocused

### ISSUE THREAD

**Issue by noto-alex-j** [albert-gonzalez/easytimer.js#13]
Thanks for an awesome package! Unfortunately I'm experiencing some strange time slow-down when I focus away from the tab or browser window that easytimer is running in. I experience the same issue on your website. The countdown slows, but does not completely stop. Do you know why this could be?

**Comment by noto-alex-j** [comment]
I found that this is possibly an issue with browser timer counting intervals and CPU usage per tab. Either way, I found a fix:
var timer = new Timer();
var started_time = new Date().getTime();
timer.start({countdown: true, startValues: {seconds: lowest_time}});

window.addEventListener('focus', function(){
    time_now = new Date().getTime();
    elapsed = (time_now-started_time)/1000;
    timeleft = parseInt(lowest_time-elapsed);
    timer.stop()
    timer.start({countdown: true, startValues: {seconds: timeleft}});
  });

I set the current time to a variable when starting the timer. The event listener updates the timer appropriately every time I refocus on the tab.

**Comment by albert-gonzalez** [comment]
Hi Alex!

It seems that the browser reduce the execution number of timeouts and it's causing the problem. Thank you for the fix. I'll try to make some changes using your idea to fix this.

Regards!

**Comment by albert-gonzalez** [comment]
Hi again!

sorry about the delay. I have just published 1.2.0 version. I refactored the counters updating and now it should work fine in any case.

I close the issue, if you need any help or if you find some other issue please tell me!

Thank you!
