### ISSUE TITLE
object returned by getTimeValues() or getTotalTimeValues() is mutated as timer runs

### ISSUE THREAD

**Issue by pavloDeshko** [albert-gonzalez/easytimer.js#134]
Ran into strange bug as I tried to 'save' specific time values for future use in my app.
[snippet](https://codesandbox.io/s/easytimer-js-values-mutation-kq3z3?file=/src/index.ts) to demonstrate the issue
I assume user should get new object with current values on every call to `getTimeValues()`? Or current behavior was intended? If yes it's little confusing. In short:
`values = timer.currentValues //another way to do it, referenced object expected to be mutated by timer`
`values = timer.getCurrentValues() //current way, returned object expected to be 'immutable', but is not`

**Comment by albert-gonzalez** [comment]
Hi!

yes, is intended. They return the same object in order to prevent some memory leak creating a copy every time that they are invoked.

If you need to save the values, you can copy them in your app. I think you could make something like `{...timer.getTimeValues()}`

Best regards!
