### ISSUE TITLE
Reset Timer doesn't reset to Zero if StartValue is not started from Zero

### ISSUE THREAD

**Issue by khallid-itdevtech** [albert-gonzalez/easytimer.js#135]
var timer = new window.easytimer.Timer();
timer.start({ startValues: { seconds: 600 }});
I have started timer from 600 Seconds  after sometime eg. on 650 timer.reset() called it doesn't reset it to 0. It start time again from 600.
I want to start from 0 Even if my initial value isn't 0.
Can You please help how can I achieve this?

**Comment by albert-gonzalez** [comment]
Hi!

Sorry for the late response.

The `reset` method resets the timer to the previously configured values. If you need to start it again from 0, you need to stop it and start it again with this configuration. For example:

```js
timer.stop();
timer.start({ startValues: { seconds: 0 }});
```

Best regards!
