### ISSUE TITLE
Timer is not defined

### ISSUE THREAD

**Issue by CyberBarby** [albert-gonzalez/easytimer.js#136]
Hi there.

Making it simple, the following code, provided "as-is" by the examples, is not working, it's giving the error "Timer is not defined":

```
var timer = new Timer();
timer.start();

timer.addEventListener('secondsUpdated', function (e) {
    $('#basicUsage').html(timer.getTimeValues().toString());
});
```

Instead it should be, based on the examples:

```
var timer = new easytimer.Timer();
timer.start();

timer.addEventListener('secondsUpdated', function (e) {
    $('#basicUsage').html(timer.getTimeValues().toString());
});
```

Now, am I doing something wrong, or are the examples not correct?

BR.

**Comment by albert-gonzalez** [comment]
Hi!

The way of importing the lib changes depending on how you are loading the library (explained here: https://github.com/albert-gonzalez/easytimer.js#library-load). The examples use the "ES6 Import" where you can instance a timer using "new Timer();". If you are loading the library using a script tag, then you have to use the other way: "new easytimer.Timer();".

Best regards!
