### ISSUE TITLE
About clear

### ISSUE THREAD

**Issue by KarlaGonzalez** [albert-gonzalez/easytimer.js#14]
Hi everyone, somebody could tell me how can I clear the values of the timer to 00:00:00 again when click another button?

Thanks

**Comment by albert-gonzalez** [comment]
Hi!

There is not exist any function to reset the counter. You can do the trick stopping and starting again the timer.

I'll try to add a reset function to the library.

Best regards!

**Comment by albert-gonzalez** [comment]
Hi!

I have just published 1.3.0 version with a new function called reset. This function resets and restarts the timer. I hope it helps!

Best regards!

**Comment by KarlaGonzalez** [comment]
Wow thank´s, sure it would helps!

:)
