### ISSUE TITLE
Double Digit Support

### ISSUE THREAD

**Issue by pirex360** [albert-gonzalez/easytimer.js#140]
Hi There,

Thanks for your great library.
Is there an option to have double digits display? 

timer.getTimeValues().seconds , ex: 4 seconds , could be 04 seconds instead....

Best Regards,

**Comment by albert-gonzalez** [comment]
Hi!

First of all, thank you for your kind words!

The library does not offer this feature. The counters are integers, and you can convert them the way you want to. In your case, you can use the function padStart (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) to add the 0. You can do something like this:

```js
let stringSeconds = String(timer.getTimeValues().seconds).padStart(2, '0');
```

Best regards!

**Comment by pirex360** [comment]
Ok, thanks for pointing to a solution.

Congratulations for your work.

**Comment by albert-gonzalez** [comment]
You are welcome!

Best regards!
