### ISSUE TITLE
Hour > 24

### ISSUE THREAD

**Issue by pirex360** [albert-gonzalez/easytimer.js#142]
Hi, thanks for your work.

I use the diff method to calculate the difference in seconds from two dates, all good ... but one of the intervals exceeds more than one day, example: seconds: 287121 (more or less 79h and 45minutes)

I want to appear in timer.getTimeValues().hours = 79 H.... but it shows only 7 Hours...the rest is in the .days method, it appear 3 days.
So my question is about limiting the getTimeValues, to max Hours...or Minutes per example.... 

I have a billboard system, showing time difference in [H] [M] [S], so imagine 25Hour+10Minutes+5Seconds difference, should appear [25]H [10]M [05]S and not [01]H [10]M [05]S (+1Day)

Thank you

NOTE: for now I used this hack to get it to work, but I think it could be an option in your library, and if exists, excuse me I did not find in the documentation.

`let realhours = timer.getTimeValues().days > 0 ? (timer.getTimeValues().days * 24) + timer.getTimeValues().hours : timer.getTimeValues().hours;`

**Comment by albert-gonzalez** [comment]
Hi!

If you want the totals, you can use `timer.getTotalTimeValues().hours`

Check out this example: https://runkit.com/albert-gonzalez/6271690754fec1000821a907

Best regards!

**Comment by pirex360** [comment]
Thank you
