### ISSUE TITLE
How to get secondHundreth?

### ISSUE THREAD

**Issue by Hassan-YB** [albert-gonzalez/easytimer.js#144]
It's not an issue but I need a solution if you could help.
Your Js code is not well commented and I can't figure how to receive secondHundreth and secondTenth combine.

**Comment by albert-gonzalez** [comment]
Hi!

The maximum precision you can get is secondTenths. Check out this example to see the available precisions: http://albert-gonzalez.github.io/easytimer.js/#gettingTimeValuesExample

Best regards!
