### ISSUE TITLE
Rewrite in typescript

### ISSUE THREAD

**Issue by baseplate-admin** [albert-gonzalez/easytimer.js#153]
Hi,

Thanks for this awesome project.

I was wondering if you were willing to move to `typescript` for this project. That would be better for maintainability in the long run.

Thanks :D

**Comment by albert-gonzalez** [comment]
Hi!

I am glad you like it :).

There are no plans to rewrite it in TS. It's an old project, and only I maintain it updating the dependencies. The last change in the source code was two years ago.

I hope you understand.

Best regards!
