### ISSUE TITLE
Is this timer accurate?

### ISSUE THREAD

**Issue by harley01** [albert-gonzalez/easytimer.js#18]
I noticed the code uses setInterval for the timer. 
setInterval isn't exactly accurate at measuring time, see here: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified

I assumed the code would be compensating for this somehow, but couldn't see anything about that. 

Is the timer accurate?

**Comment by albert-gonzalez** [comment]
Hi!

I refactored the timer to make it accurate in the 1.3.0 version for fixing the issue #13 . It uses setInterval for updating the counters, but the passed time is always calculated using the difference between the current time and the time when the timer was activated.

If you find some issue tell me and I'l try to fix it.

Best Regards!

**Comment by harley01** [comment]
That's great, thanks very much! 
This is just a suggestion, but it might be worth mentioning that the timer is accurate in the README.md, I think this project would gain more traction from the community with that mentioned.
