### ISSUE TITLE
Countdown skips a second at the beginning

### ISSUE THREAD

**Issue by harley01** [albert-gonzalez/easytimer.js#19]
See the problem here: https://albert-gonzalez.github.io/easytimer.js/#countdownTimerExample 

The countdown goes 30 and straight to 28, skipping 29.
I had the same issue when using easytimer.js locally.

**Comment by albert-gonzalez** [comment]
Hi!

Thank you for opening the issue. I have just fixed it and published 1.3.2 version with the fix. You can see in the example that now is working ok.

Best regards!

**Comment by harley01** [comment]
Great, that was quick! Thanks 👍
