### ISSUE TITLE
Countdown timer achieves target with 0.9 seconds remaining.

### ISSUE THREAD

**Issue by hayrich** [albert-gonzalez/easytimer.js#2]
The targetAchieved event fires when there is still 0.9 seconds left on the clock. This bug occurs when the precision is tenths of a second.

**Comment by albert-gonzalez** [comment]
Hi!

Thank you very much for your pull request. I have just merged and published the version 1.0.2 with your fix.

Regards!

**Comment by hayrich** [comment]
No worries Albert,

Happy to help.
Your timer works well, thanks.

Richard
