### ISSUE TITLE
More than 24h

### ISSUE THREAD

**Issue by williansebastiao** [albert-gonzalez/easytimer.js#22]
Is it possible to work longer than 24 hours?
Example: I worked a full year on the specific task, so I have 8766h
It's possible?

Hugs!

**Comment by albert-gonzalez** [comment]
Hi!

I haven't tested an extreme case like this, but I think it will work. The timer counts days, hours, minutes, seconds and tenths of second.

Regards!

**Comment by williansebastiao** [comment]
Hello!
I did a test and only counts 24h. How can I change to more than 24h?
Hugs!

**Comment by albert-gonzalez** [comment]
Hi again,

I have tested in the examples pages and it seems to work ok with more than 24 hours. You can try this code that will start a Timer starting since 25 hours and it will update every second some html elements with the time values:

```js
var timer = new Timer();
  timer.start({startValues: { hours: 25 }});
  timer.addEventListener('secondsUpdated', function (e) {
    $('#gettingValuesExample .days').html(timer.getTimeValues().days);
    $('#gettingValuesExample .hours').html(timer.getTimeValues().hours);
    $('#gettingValuesExample .minutes').html(timer.getTimeValues().minutes);
    $('#gettingValuesExample .seconds').html(timer.getTimeValues().seconds);
    $('#gettingValuesExample .secondTenths').html(timer.getTimeValues().secondTenths);

    $('#gettingTotalValuesExample .days').html(timer.getTotalTimeValues().days);
    $('#gettingTotalValuesExample .hours').html(timer.getTotalTimeValues().hours);
    $('#gettingTotalValuesExample .minutes').html(timer.getTotalTimeValues().minutes);
    $('#gettingTotalValuesExample .seconds').html(timer.getTotalTimeValues().seconds);
    $('#gettingTotalValuesExample .secondTenths').html(timer.getTotalTimeValues().secondTenths);
  });
```
This code is very similar to this demo example: http://albert-gonzalez.github.io/easytimer.js/#gettingTimeValuesExample

I hope this example helps you

Best regards!

**Comment by tomhe2x** [comment]
This isn't true i can't get the time to start off with values more then 24 hours and then increase

**Comment by albert-gonzalez** [comment]
Hi,

It should be possible. I created this example in which a timer starts with a value of 25 hours.

https://runkit.com/albert-gonzalez/5cb4bcd26ae70b001211c200

If you have problems with your code, please give me an example and I will try to help.

Best regards!
