### ISSUE TITLE
startValues

### ISSUE THREAD

**Issue by farshadfahimi1371** [albert-gonzalez/easytimer.js#23]
is it possible to give second to easytimer for startValue
if we could so how should I do that???

**Comment by albert-gonzalez** [comment]
Hi!

yes, it is possible, you can do something like this:

```js
var timer = new Timer();
timer.start({precision: 'seconds', startValues: {seconds: 90}, target: {seconds: 120}});
```

Check out the complete example here: http://albert-gonzalez.github.io/easytimer.js/#startAndTargetValuesExample

Best regards!
