### ISSUE TITLE
Question: Is there a way to preset the time before start?

### ISSUE THREAD

**Issue by gitllermopalafox** [albert-gonzalez/easytimer.js#24]
Hi,

I'd like to preset the time before start, in my case seconds... for example:

I want to show: 00:00:10 before start (I need to count and no to countdown).

Is there a default way to do that? Can you advice me?

Saludos y gracias por el plugin.

**Comment by albert-gonzalez** [comment]
Hi!

No, you can't preset the time before starting. If you need something like this you can start with the value that you need and pause the timer. Check out this example:

```js
var timer = new Timer();
timer.start({precision: 'seconds', startValues: {seconds: 90}});
timer.pause();
```

Best regards!
