### ISSUE TITLE
'secondTenths' show hundredth of a second...

### ISSUE THREAD

**Issue by evertonlbaroni** [albert-gonzalez/easytimer.js#25]
.html(timer.getTimeValues().toString([ 'minutes', 'seconds', 'secondTenths']));

Current: 00:00:00, 00:00:02 ...  00:00:09, 00:01:00...
Right: 00:00:10, 00:00:20 ...  00:00:90, 00:01:00...

Example: http://cronometronline.com.br/

**Comment by albert-gonzalez** [comment]
Hi!

I know it's a bit late, but... I have just fixed this issue. The fix is in the version 2.0.2. e.g. The format of to String in the case of tenth of a second is 00:00:2

Best Regards!
