### ISSUE TITLE
How to integrate LocalStorage ?

### ISSUE THREAD

**Issue by oneezy** [albert-gonzalez/easytimer.js#26]
How can we integrate `localStorage` to the timer? For example, I'd like to create a start/stop timer and pause the page whenever I leave..., then when returning to the page it remembers my value and resumes. 

Would this be an easy integration ?

Thanks for a great plugin!

**Comment by albert-gonzalez** [comment]
Hi!

First of all, sorry for the delay...

I don't think that my answer will be useful for you now, but maybe helps someone else! You can save the current value in the localStorage every time is updated, and when the page is reloaded, initialize the timer with this startValue.

Example:

```js
// You have localStorageValueInSeconds variable with the last value saved
timer.start({precision: 'seconds', startValues: {seconds: localStorageValueInSeconds}});
```

Best Regards!
