### ISSUE TITLE
There's a way to Reset the countedown timer

### ISSUE THREAD

**Issue by lokharth** [albert-gonzalez/easytimer.js#27]
I want my countdown timer to reset itself and start again using the targetAchieved i've tried doing it like this:

	timer.addEventListener('targetAchieved', function (e)
	{
		timer.reset();
	});

Got no results

**Comment by albert-gonzalez** [comment]
Hi!

There was a bug in the targetAchieved event that caused this issue. I have just fixed it and published the version 2.0.1 with the fix.

Best regards!
