### ISSUE TITLE
How to show days in hours?

### ISSUE THREAD

**Issue by imatsu** [albert-gonzalez/easytimer.js#28]
Is it possible to show days in hours? or, the minute hand continue counting after 24 hours?

Example:

1d 14h 10m 12s = 38:10:12

**Comment by albert-gonzalez** [comment]
Hi!

Yes, you have getTotalTimeValues function, that shows the accumulated time units. Example:

```js
timer.start({precision: 'seconds', startValues: {hours: 50 }});

timer.addEventListener('secondsUpdated', () => {
    console.log(timer.getTotalTimeValues());
});
```

In this example, every second the console will show an object with the values: {days: 2, hours: 50, minutes: 3000, …}. You can get this values a format them whatever you want.

Best regards!
