### ISSUE TITLE
Countdown timer doesn't show days

### ISSUE THREAD

**Issue by frankenstein-uk** [albert-gonzalez/easytimer.js#29]
Hi there, maximum allowed number of seconds is equivalent to 3600 x 24. Otherwise it only shows remaining hours.

for e.g. if 48 x 3600 is passed, it would count down from 24:00:00 rather 01:24:00:00

Also small feature request. There could be setting that would allow to hide unused zeroes. For e.g.:

instead: 00:01:59, it could show 01:59 if setting hide_zeroes:true

**Comment by albert-gonzalez** [comment]
Hi!

The toString function is very simple for now, but you can pass units that you want to show. For example:

```js
timer.getTimeValues().toString(['days', 'hours', 'minutes', 'seconds'])
```

I'll try to add an parameter called auto for showing only the units that have values.

Best regards!

**Comment by andresprogra** [comment]
Sorry, but the days show me the value double
Example

days = 5
days show me = 10

Gracias, @albert-gonzalez

**Comment by albert-gonzalez** [comment]
Hi!

Could you show me an example of your problem?

**Comment by andresprogra** [comment]
Of course @albert-gonzalez !

`
this.timer.start({
      startValues: {
        days: 3,
        hours: 5,
        minutes: 20,
        seconds: 23,
      }
    });
`

Easy timer show me:
06:05:20:23

**Comment by albert-gonzalez** [comment]
I tried again and it worked for me! 😶 

Maybe are you using an old version? I tried this example:

```js
var Timer = require("easytimer.js")
var timer = new Timer();

timer.start({ startValues: { days: 3, hours: 5, minutes: 20, seconds: 23 } });

timer.addEventListener('secondsUpdated', () => {
    console.log(timer.getTimeValues().toString(['days', 'hours', 'minutes', 'seconds']));
});
```

You can try it here: https://runkit.com/albert-gonzalez/easytimer-test

Thank you for your time!
