### ISSUE TITLE
startValues cannot be negative.

### ISSUE THREAD

**Issue by michaelkoelewijn** [albert-gonzalez/easytimer.js#30]
I would like my timer to start at -4 seconds.
Is this easy to implement?

`this.timer.start({
            precision: 'secondTenths',
            startValues: [0,-4,0,0,0]
        });`

**Comment by albert-gonzalez** [comment]
Hi!

It seems strange that a timer uses negative values. Why do you need this feature? Maybe you can use the timer in a more common way.

Best regards!

**Comment by michaelkoelewijn** [comment]
I'm creating a workout app for our office. I'll spare you the details on this but i need the timer to start at -4 seconds as we need this for preparation time as we cannot start a workout instantly.
Of course i can create a workaround, but a native solution would be better.

**Comment by albert-gonzalez** [comment]
It has sense. Give me a few days and I'll try to make a new version with this feature. For now, you could use 2 differents timers, one for the countdown and another for counting the time that will start when the countdown finishes.

Best regards!

**Comment by michaelkoelewijn** [comment]
Thanks albert. I'll keep an eye out for any changes.
For now i'll add that second timer.

**Comment by albert-gonzalez** [comment]
Hi again, Michael!

I have just published v2.1.0. Now you can use negative values in startValues and target params. I hope it helps you.

Regards!

**Comment by michaelkoelewijn** [comment]
Hi Albert,

Thanks for the new release!
I'll update the package tomorrow and change my code.
