### ISSUE TITLE
TypeError: this.sendTimer.reset is not a function

### ISSUE THREAD

**Issue by mprevot** [albert-gonzalez/easytimer.js#32]
I got 

```
this.sendTimer = new Timer();
this.sendTimer.start({precision: 'seconds', target: {seconds: 2}});
```

but later,  ` this.sendTimer.reset();`

gives the bug.

**Comment by albert-gonzalez** [comment]
Hi,

I tried it and everything went ok. Maybe were you using an old version of the library? The reset function was included in the version 1.3.0. The code I tried is this:

```js
var Timer = require("easytimer.js")

this.sendTimer = new Timer();
this.sendTimer.start({precision: 'seconds', target: {seconds: 2}});

let that = this;

setTimeout(function () {
    that.sendTimer.reset();
    console.log('reset');
}, 3000);
```

Sorry for the delay.

Best regards!

**Comment by mprevot** [comment]
Hello,

It looks like the package version on npm is 1.1.1 max. (It is referenced in
packages.json and packed with webpack.)

$ npm i easytimer@1.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for easytimer@1.3
npm ERR! notarget In most cases you or one of your dependencies are
requesting
npm ERR! notarget a package version that doesn't exist.

M


2018-03-22 20:32 GMT+01:00 Albert González <notifications@github.com>:

**Comment by albert-gonzalez** [comment]
Hi again,

you are using a fork of this library that is published in npm with a similar name. I made improvements since that fork was made, and the actual version is 2.1.0. You can install it with:

```
npm install easytimer.js
```

Best Regards!

**Comment by albert-gonzalez** [comment]
You are welcome :)
