### ISSUE TITLE
Is that possible to use this with React Native?

### ISSUE THREAD

**Issue by Rutulpatel7077** [albert-gonzalez/easytimer.js#34]
Can we override and set values by our self of this timer?

**Comment by albert-gonzalez** [comment]
Hi,

no, you can't override the values. You initialize the counter with some configuration, and in order of this, the counter calculates the values. I don't know the restrictions of React Native, but this timer has no dependencies and I think it would be easy to adapt it to this technology.

Best Regards!

**Comment by Rutulpatel7077** [comment]
@albert-gonzalez  Thank you so much for your reply. 
Really nice! Package..
