### ISSUE TITLE
Bug in "Interval of Tenth of Seconds"-Example

### ISSUE THREAD

**Issue by suko16** [albert-gonzalez/easytimer.js#36]
The code below worked for me. The bold words were wrong in the original code on the website.
The "secondTenthsUpdated" was "secondsUpdated" and the "getTimeVaules()" was "callbackTimer()".

var timer = new Timer();
timer.start({precision: 'secondTenths'});
timer.addEventListener('**secondTenthsUpdated**', function (e) {
    $('#secondTenthsExample .values').html(timer.**getTimeValues()**.toString(['hours', 'minutes', 'seconds', 'secondTenths']));
});

**Comment by albert-gonzalez** [comment]
Hi!

You are right! The behaviour was correct but the example code was wrong. I have just fixed it :)

Thank you very much!
