### ISSUE TITLE
Adjust size of the Clock face

### ISSUE THREAD

**Issue by kumaunix** [albert-gonzalez/easytimer.js#39]
I was looking through the flipclock.css where I could adjust the size of the clock. I wish to make it small, 

could you advise?

**Comment by albert-gonzalez** [comment]
Hi!

This library does not use any styles, you can use the styles that you want!

**Comment by kumaunix** [comment]
oh okay.... I have to work with the flipclock.css and find the attributes there ... thanks albert

**Comment by albert-gonzalez** [comment]
Maybe it's from another library...

You are welcome 😉
