### ISSUE TITLE
set starting timer?

### ISSUE THREAD

**Issue by socieboy** [albert-gonzalez/easytimer.js#4]
It's possible to set a starter time?

instead of start the counter at 00:00:00, timer.setInitTime(00,12,32)
And the result will be timer.start() 00:12:32?

**Comment by albert-gonzalez** [comment]
Hi!

Yes, you can set the init time passing the startValues option, like this:

`timer.start({startValues: {minutes: 12, seconds: 32});`

You can check out more usage examples here: http://albert-gonzalez.github.io/easytimer.js/

Best regards!

**Comment by socieboy** [comment]
Thank you!
