### ISSUE TITLE
HELP - Many instances

### ISSUE THREAD

**Issue by trevobr** [albert-gonzalez/easytimer.js#40]
Could I to instantiate many Timers on same page? Each one with your behaviour?

**Comment by albert-gonzalez** [comment]
Hi!

Yeah, check out this example:

https://runkit.com/albert-gonzalez/5af1d31773b6190012b7d4dd

I configured two timers: one in normal mode and another in countdown mode. Each timer has a listener that prints a console.log with the current value of its value.

Best regards!

**Comment by trevobr** [comment]
Im trying to do a more advanced thing.

I have a DOM with 3 timers. So I want to instantiate each of them dinamically. Now , I can just to maintain the last one after iteration. 

I'm using a makeTimers function... take a look ...see if you can give me a light! 

https://gist.github.com/trevobr/6a7882373376a1a4d0c01113537b57f6

**Comment by albert-gonzalez** [comment]
In line 29:

```js
 local = '#arrayexample'+i;
```

try to change it to: 
```js
var  local = '#arrayexample'+i;
```

If you don't put var, it's a global variable and all the listeners are sharing it. Try this and let me know the result :)

By the way, in javascript arrays are dynamic, you can initialize them just with variable = [];

Best regards!
