### ISSUE TITLE
HELP - Random timers dinamically - almos there Albert! 

### ISSUE THREAD

**Issue by trevobr** [albert-gonzalez/easytimer.js#42]
Hi Albert! First of all , thanks for the support. 
I've did another example where I created random number to initate the timer. 

https://gist.github.com/trevobr/37b7e9947a33a3a939ff154f2e7e178a

I want to know if is there an elegant way to accomplish this. As i commented at line 23 , i've tried to iterate using for index to setinterval on locators. But

**Comment by albert-gonzalez** [comment]
Hi!

Why did you use setInterval? You could do that with the addEventListener method.

Can you write the example with the iteration error?

**Comment by albert-gonzalez** [comment]
Related to #40 #41. I am going to close these other issues.

**Comment by albert-gonzalez** [comment]
I close the issue. If you need more help, please reopen.
