### ISSUE TITLE
Multiple timers, each with a button

### ISSUE THREAD

**Issue by Hilgon** [albert-gonzalez/easytimer.js#43]
Hello, thanks for the help.

So on my page I have a list of multiple tasks and each task has a timer next to it. 
I have been trying to "attach" each timer to it's task. The only problem is that I'm stuck at getting the correct time value to the right task.

If I use the function `timer.getTimeValues()`, it only takes the value of the first timer it can find.
Is it possible to make it so I can get the correct time values for each task?

The function of the eventListener is like this
```
	timer.addEventListener('secondsUpdated', function (e) {
		$('.task-status').each(function() {
			if($(this).hasClass('task-stop')) {
				$(this).parent().parent().find('.task-timer').html(timer.getTimeValues().toString());
			}
		});
	});
```

Thanks!

**Comment by albert-gonzalez** [comment]
Hi!

try to initialize a timer for every task that needs a timer. I don't know if this is the exact case, but you can do something like this:

```js
$('.task-status').each(function() {
    if ($(this).hasClass('task-stop')) {
        var timer = new Timer();
        timer.addEventListener('secondsUpdated', function (e) {		
	    $(this).parent().parent().find('.task-timer').html(timer.getTimeValues().toString());
        });
        timer.start();
    }
});
```

If you need to interact with them later, you can store timers in some array or object.

Best regards!

**Comment by albert-gonzalez** [comment]
I close the issue. If you need more help, please reopen.
