### ISSUE TITLE
Reset Countdown

### ISSUE THREAD

**Issue by thisisfed** [albert-gonzalez/easytimer.js#46]
Hello and thanks for this useful .js. I was wondering, is there a way I can reset a countdown even before it reaches 0? Thanks.

**Comment by albert-gonzalez** [comment]
Hi!

Yes, you can reset the counter to the initial values with the reset function.

You can check out this example: http://albert-gonzalez.github.io/easytimer.js/#chronometerExample

If you need a specific behavior tell me about it and I will help you.

**Comment by thisisfed** [comment]
Hi @albert-gonzalez, thanks for your reply. 
Actually yes, would be great if you can help.

The timer starts when the user is idle for 10 seconds. I just want it to stop and reset when the user becomes active again and I can't figure it out how to do it.

**Comment by thisisfed** [comment]
@albert-gonzalez it's what I'm doing the thing is that the STOP / RESET isn't working or maybe it sees two different timers?

**Comment by albert-gonzalez** [comment]
Ah! Yes, the timer has to be the same instance. Every instance of the timer works independently. You must use the same instance to start/stop/reset the timer. For example, you have to create an instance with `var timer = new Timer()` and then user the variable timer in the different events.

**Comment by thisisfed** [comment]
But it's what I'm doing.

START

```
var timer = new Timer();
timer.start({countdown: true, startValues: {seconds: 218}});
$('#timer .values').html(timer.getTimeValues().toString());
timer.addEventListener('secondsUpdated', function (e) {
$('#timer .values').html(timer.getTimeValues().toString());
});
```

STOP / RESET

```
var timer = new Timer();
timer.stop();
timer.reset();
timer.addEventListener('reset', function (e) {
$('#timer .values').html(timer.getTimeValues().toString());
});
```

**Comment by albert-gonzalez** [comment]
you are initializing the timer twice. You must do something like this:

```js
var timer = new Timer(); // unique instance of the timer

// START EVENT

timer.start({countdown: true, startValues: {seconds: 218}});
$('#timer .values').html(timer.getTimeValues().toString());
timer.addEventListener('secondsUpdated', function (e) {
$('#timer .values').html(timer.getTimeValues().toString());
});

// RESET EVENT

timer.stop();
timer.reset();
timer.addEventListener('reset', function (e) {
$('#timer .values').html(timer.getTimeValues().toString());
});
```

**Comment by thisisfed** [comment]
@albert-gonzalez I just tried but like this not even the countdown is workin'.

**Comment by albert-gonzalez** [comment]
Does the console show any error? Could you give me a full example of the problem? Maybe using some jsfiddle.

**Comment by thisisfed** [comment]
It's here buit it's not working: http://jsfiddle.net/hdypvjzt/

**Comment by albert-gonzalez** [comment]
Hi Federico, I am sorry for the delay.

I made a simple example that has a similar behavior that the one you told me. If the user doesn't move the mouse in 3 seconds, the timer starts, if the user moves the mouse, the timer stops. I hope it helps you.

http://jsfiddle.net/xpvt214o/266016/

Best regards.

**Comment by thisisfed** [comment]
Thank you so much @albert-gonzalez!

**Comment by albert-gonzalez** [comment]
You are welcome :)
