### ISSUE TITLE
No Licence Issued with Repository

### ISSUE THREAD

**Issue by Pinaz9** [albert-gonzalez/easytimer.js#48]
There is currently no licence associated with easytimer.js . This makes it legally impossible to use your software without written permission, as the default licence here as anywhere else is All Rights Reserved. Any software professional familiar with the issue will not touch your code with a ten foot pole.

I would like to use your library for an open source project, however, until such time as you give me written permission (in the form of a licence or not), I am unable to do so legally.

I suggest you visit [Github's article](https://help.github.com/articles/licensing-a-repository/) on the matter. I chose GNU GPL v3.0, as I want my software to be shared-alike, but that's just me.

**Comment by albert-gonzalez** [comment]
Hi Patrick!

Being honest, I forgot to create the LICENSE file. The library has MIT license, you can use it without any problem.

I will add the license file asap.

Best Regards!

**Comment by Pinaz9** [comment]
I didn't even know how big of a deal it was until a few weeks ago. Thanks, man!

**Comment by albert-gonzalez** [comment]
Now you can see the LICENSE in the repo :). I published the version 2.2.3 with the change.

I close the issue. If you need more help just tell me.

Best Regards!
