### ISSUE TITLE
targetAchieved undocumented.

### ISSUE THREAD

**Issue by luismanolo** [albert-gonzalez/easytimer.js#50]
Hi Albert.
You should add "targetAchieved" event to the README.md documentation.

Thanks for your work.

**Comment by albert-gonzalez** [comment]
Hi!

Thank you! I forgot to add this event to the documentation. I'll add it in the next few days.

Best regards!

**Comment by albert-gonzalez** [comment]
Finally I updated the README with this event a some others that were missing too.

Thanks!
