### ISSUE TITLE
Change time method?

### ISSUE THREAD

**Issue by taylordwright44** [albert-gonzalez/easytimer.js#51]
I'm interested in using this as a synchronization tool by synching videos/music up with the timer through sockets.

Does this have a method of changing time? Say you're at 55 seconds and you want to change time to 22 seconds?

**Comment by albert-gonzalez** [comment]
Hi!

No, the library doesn't have this method. The only way to do this would be to stop the timer and start again with the new values.

Best regards!

**Comment by taylordwright44** [comment]
all good, I built my own. Thanks for the response!

**Comment by albert-gonzalez** [comment]
You are welcome :)
