### ISSUE TITLE
Resume option not available 

### ISSUE THREAD

**Issue by sandipamukherjee** [albert-gonzalez/easytimer.js#52]
There must be a resume option. Is it possible to implement resume option here. Please reply. @albert-gonzalez

**Comment by albert-gonzalez** [comment]
Hi!

If you pause the timer with the pause method, then you can resume it with the start method (without any parameter). I have updated the README with this information.

Best Regards!

**Comment by sandipamukherjee** [comment]
First of all heartiest thanks for your plugin. Its help me a lot. Great plugin. No glitch!
