### ISSUE TITLE
ES6 Imports?

### ISSUE THREAD

**Issue by mcblum** [albert-gonzalez/easytimer.js#53]
Hey! Thanks for the package. For some reason when doing `import * as Timer from 'easytimer.js';` I get the error `File '/project/node_modules/easytimer.js/index.d.ts' is not a module.`

Any idea how to fix that? If I can get it to compile, it appears it does actually work.

**Comment by albert-gonzalez** [comment]
Hi!

Have you tried `import Timer from 'easytimer.js'`? It should work this way.

Best Regards!

**Comment by rgsone** [comment]
Works fine with `import Timer from 'easytimer.js';` here.

**Comment by albert-gonzalez** [comment]
Hi!

Finally, I solved this issue. I had to change the export of the library, so there is a breaking change in the way to import the library. I made a little migration guide with these changes: https://github.com/albert-gonzalez/easytimer.js/blob/master/MIGRATION.md.

Now you should import without any problem in ES6 or Typescript:
`import Timer from 'easytimer.js'
or
`import { Timer } from 'easytimer.js'`

The version with this fix is v3.0.0. 

Best Regards!
