### ISSUE TITLE
How to set countdown timer initial value without starting?

### ISSUE THREAD

**Issue by garyo** [albert-gonzalez/easytimer.js#54]
Seems like the only public API to pass params is `timer.start(params)`. I'd like to initialize a countdown timer but not start it yet. Any way to do that?

**Comment by albert-gonzalez** [comment]
Hi!

no, you can't do that. You can do some workarounds:
```js`
timer.start(params);
timer.pause();
// Other code here
timer.start();
```
or
```js`
timer.config = params;
// Other code here
timer.start(timer.config);
```

I hope it helps.

Best Regards!
