### ISSUE TITLE
Pause button = resume function

### ISSUE THREAD

**Issue by captainscorch** [albert-gonzalez/easytimer.js#55]
Hello,

thanks for creating the great timer script!
I am aware of the "pause" button from your sample page, my problem is I only have 3 buttons. Start, Pause/Resume and Stop. The Pause button should resume the timer when clicked again after being paused.

I tried to change the class after the click on the pause button from "pauseButton" to "startButton" but this didn't help. Is there anyway to do this?

Here's my HTML:
`            <div id="controls" class="recordingTime">
             <button id="recordButton" class="startButton" onclick="displayStopwatch()"><i class="fas fa-microphone"></i></button>
             <button id="pauseButton" class="pauseButton" disabled><i class="fas fa-pause"></i></button>
             <button id="stopButton" class="stopButton" disabled><i class="fas fa-stop"></i></button>
            </div>`

That's my current timer code:
`// show recording time
var timer = new Timer();
$('.recordingTime .startButton').click(function () {
    timer.start();
});
$('.recordingTime .pauseButton').click(function () {
    timer.pause();
});
$('.recordingTime .stopButton').click(function () {
    timer.stop();
});
timer.addEventListener('secondsUpdated', function (e) {
    $('.recordingTime .values').html(timer.getTimeValues().toString());
});
timer.addEventListener('started', function (e) {
    $('.recordingTime .values').html(timer.getTimeValues().toString());
});`

**Comment by albert-gonzalez** [comment]
Hi!

You can define a flag and use it to pause/resume the timer using the pause button. Something like this:

```js
var paused = false;
$('.recordingTime .pauseButton').click(function () {
  if (paused) {
    paused = false;
    timer.start();
  } else {
    paused = true;
    timer.pause();
  }
}); 
```

I hope this helps you.

Best regards!
