### ISSUE TITLE
startValues only works once

### ISSUE THREAD

**Issue by tifDev** [albert-gonzalez/easytimer.js#56]
My timer looks like this: http://oi64.tinypic.com/vdeqeo.jpg

The _set_ button is to allow the user to put a custom value and the timer starts from it. Here is the code:
```
    btnSet.addEventListener( "click", function () {

        let sec = Number( document.querySelector( '.sec' ).value );
        let min = Number( document.querySelector( '.min' ).value );
        let hour = Number( document.querySelector( '.hour' ).value );

        let config = {
            startValues: {
                seconds: sec,
                minutes: min,
                hours: hour
            }
        };

        timerInstance.start( config );
    } );
```
 
**This works, but only once (and if i dont click on start button before). If i want to set the timer value more than 1x it doesn't work. What is the solution for this?**

**Comment by albert-gonzalez** [comment]
Hi!

The config is set when you call the start function and the timer is stopped, it is does nothing otherwise. It should work if you call the stop function before you call the start function.

Another approach is to store the start values in a variable defined outside the btnSet click event, and then start the timer with this stored config when you click the start button. Something like this:

```js
    let config;
    btnSet.addEventListener( "click", function () {
        let sec = Number( document.querySelector( '.sec' ).value );
        let min = Number( document.querySelector( '.min' ).value );
        let hour = Number( document.querySelector( '.hour' ).value );

        config = {
            startValues: {
                seconds: sec,
                minutes: min,
                hours: hour
            }
        };
    } );

    btnStart.addEventListener( "click", function () {
        timerInstance.stop();
        timerInstance.start( config );
    }

```

Best regards!

**Comment by tifDev** [comment]
Thanks a lot, wish you all the best in life!

**Comment by albert-gonzalez** [comment]
You are welcome :)
