### ISSUE TITLE
Update version on cdn

### ISSUE THREAD

**Issue by machinek56** [albert-gonzalez/easytimer.js#60]
Hi! Can you update lib on cdn [https://www.jsdelivr.com/package/npm/easytimer](https://www.jsdelivr.com/package/npm/easytimer) to latest version? 
Thanks!

**Comment by machinek56** [comment]
@jimaek, oh really, thanks! :)

**Comment by albert-gonzalez** [comment]
Thanks, @jimaek !! In fact, the outdated one is a fork that some developers made from my library years ago. The updated one is the URL that Jimaek said.

Best regards!
