### ISSUE TITLE
Library load issue via script

### ISSUE THREAD

**Issue by sebagruia** [albert-gonzalez/easytimer.js#61]
Hello,

I've downloaded the library via npm and then used the library load method to use it, but when I write 
var timer = new Timer(); I'm getting this error: "Uncaught ReferenceError: Timer is not defined", do you know what the problem might be?

Thanks.

**Comment by albert-gonzalez** [comment]
Hi!

with v3.0, you have to create a instance like this:

```
var timerInstance = new easytimer.Timer();
```

I hope it helps.

Best Regards!

**Comment by sebagruia** [comment]
Hello,
Thanks for your response. It's not working I'm getting this error:  Uncaught ReferenceError: easytimer is not defined.
Here is my project's link  https://github.com/sebagruia/Project-2

Thanks

**Comment by Moe007** [comment]
Was having the same issue.

`var timerInstance = new easytimer.Timer();`

Worked for me.

**Comment by albert-gonzalez** [comment]
Hi again @sebagruia 

I checked your HTML, you have to change the script loading order. First load the easytimer lib and then your app. It should work then.

Best regards!

**Comment by Moe007** [comment]
@sebagruia You need to load the easytimer.js file before your app.js

Have this:
`<script src="lib/easytimer/dist/easytimer.min.js"></script>`
Above this:
`<script src="js/app.js"></script>`

**Comment by albert-gonzalez** [comment]
Thanks for the example @Moe007 , we answered at the same time :).

**Comment by sebagruia** [comment]
Yes, it makes a lot of sense. Thanks guys. Everything is ok now.
