### ISSUE TITLE
Can't only display seconds

### ISSUE THREAD

**Issue by Mazalucas** [albert-gonzalez/easytimer.js#62]
Hi! I've been trying to only display seconds countdown but failed.
I don't want to see "00:00:30", is it possible to only display the "30"?

Thank you Albert!

**Comment by albert-gonzalez** [comment]
Hi!

Yeah, you can get only the seconds. For example:

```js
timer.getTimeValues().seconds
```

I hope it helps.

Best regards!

**Comment by Mazalucas** [comment]
Worked perfectly!
Thank you very much :D

**Comment by albert-gonzalez** [comment]
You are welcome :)
