### ISSUE TITLE
All events work except for reset()

### ISSUE THREAD

**Issue by OmniHomogenize** [albert-gonzalez/easytimer.js#65]
I am able to use all methods ( play, stop, pause ) except for the reset method. When trying to use the reset method the console says the TypeError: timer.reset is not a function.

Am I doing something wrong or was the reset method removed from the plugin?

Thank you,
Travis

**Comment by albert-gonzalez** [comment]
Hi!

If reset method does not exist means that you are using an old version. Use the newest version and will be able to use it. Be sure that you are using this npm package: https://www.npmjs.com/package/easytimer.js

Best regards!
