### ISSUE TITLE
Add or Minus time from the timer

### ISSUE THREAD

**Issue by JonFranklin301** [albert-gonzalez/easytimer.js#66]
Is it possible to add or minus time from the timer?
I use the timer for timing sport and there are occasions when we may start the timer too early or a few seconds late.

It would be good if there was a function to add or minus time from the timer where it instantly bumps it up or down by the time specified whilst the timer is running, for example:

````Javascript
timer.addTime(2)   // Adds 2 seconds onto the timer
timer.addTime(-3)  // Minus 3 seconds from the timer or
timer.minusTime(1) // Minus 1 second from the timer
````

**Comment by albert-gonzalez** [comment]
Hi!

Thank you for opening the issue. It sounds interesting, but I prefer to keep the library as simple as possible. If you need this feature, you can get the current values of a timer and restart it adding or removing the units that you want.

Best regards!
