### ISSUE TITLE
TypeError: this.setState is not a function

### ISSUE THREAD

**Issue by BakerShoeMaker** [albert-gonzalez/easytimer.js#67]
I'm working in React and I'm setting the value of the local state to the value of the current time with the event listener parameter 'secondsUpdated'. I'm assuming that this would set the state every second. However, I keep getting this error: `TypeError: this.setState is not a function`

I have tried several things and I wanted to check to see if this an issue with easytimer.js or something I'm not doing correctly in my code. Here is the code:
`//Get time in textfield

          timer.addEventListener('secondsUpdated', function(){
              currentTime = timer.getTimeValues().toString();
              this.setState({
              currentTimeDisplayedInTextfield: currentTime
              })
              console.log("Time Displayed to user:  "+currentTime);
          });`

**Comment by albert-gonzalez** [comment]
Hi!

it's not working because the listener function is executed in the Easytimer's context, so the keyword "this" does not have the object that you expect. In order to fix this, you can use an arrow function, that keeps the context. You can do something like this:
```js
timer.addEventListener('secondsUpdated', () => {
          currentTime = timer.getTimeValues().toString();
          this.setState({
          currentTimeDisplayedInTextfield: currentTime
          })
          console.log("Time Displayed to user:  "+currentTime);
      });`
```

If you want more info of arrow functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

I hope it helps.
Best regards!

**Comment by BakerShoeMaker** [comment]
Yes. Thank you. I was actually able to put it in the call back parameter like so:
`//Start timer

          if(this.props.timer_1Status==='notFinished'){
              currentTime = timer.getTimeValues().toString(['minutes', 'seconds', ]);
              console.log("timer #1 is playing");
              timer.start({
                  precision: 'seconds',
                  countdown: true,
                  startValues: {seconds: this.props.timeOfLesson_1},
                  callback: (timer)=>{
                      this.setState({
                       currentTimeDisplayedInTextfield: currentTime
                       })
                  }
              });`

Thanks for your prompt response!

**Comment by albert-gonzalez** [comment]
You are welcome! Glad it works now :)
