### ISSUE TITLE
Timer values not showing up in iphone and ipad

### ISSUE THREAD

**Issue by digbose92** [albert-gonzalez/easytimer.js#68]
Hi, I have been using easytimer for web based timers. The timer values are showing up in web browsers (chrome/firefox/safari) from Macbooks. But when I am trying to access the timers via web from ios devices(iphone/ipad), the timer values are not getting displayed.

**Comment by albert-gonzalez** [comment]
Hi!

Maybe it is incompatible with some iOS browser. Could you tell me the browser and if there is some error in the browser's development console?

Thanks!
Best Regards.

**Comment by digbose92** [comment]
Hi ,
Thanks for the response. I cross checked the issue again. There was an error in the code.  The values are showing up in browsers from ipad and iphone . The examples listed in http://albert-gonzalez.github.io/easytimer.js/ are working fine. On a side note, is there a way to integrate one of the timers with a sound button ? For example, if the counter duration is over, there should be a sound to indicate its completion. Thanks in advance

**Comment by albert-gonzalez** [comment]
Yes, if you need to play a sound when the timer completes, you can add a listener to the 'targetAchieved' event. It should be something like that:
```js
timer.on('targetAchieved', function () {
  // your code to play the sound
});
```

Best regards!
