### ISSUE TITLE
Timer keeps going, doesn't stop on timer.stop()

### ISSUE THREAD

**Issue by BakerShoeMaker** [albert-gonzalez/easytimer.js#69]
I have a count down timer where a use can enter three different times. Once one timer finishes the other starts. My logic is such that when each timer finishes I stop and reset and then start the new timer. When it comes to the last timer, no new timer should start. However, something strange happens: the stops where the text is being rendered but it keeps going in my console.log statement even though I stopped and reset the time and haven't started a new one. I'm using React and I set the logic in my App.js component so that there is no way the timer should keep going:
App.js
` //This is the last option so it has no way of starting the timer based on the conditions in state. 

else if(this.state.timeOfLesson_2 == 0 && this.state.timer_2Status==='finished'){
                this.setState({
                        timer_3Status: "finished",
                        timeOfLesson_3: 0
                    }
                );`

Here is some code from the timer component:
` //Do something when the timer stops

             timer.addEventListener('targetAchieved', ()=>{
                  this.resetTimer();
                  this.changeToNextTimer(); // this is a method in App.js
              });

  resetTimer = ()=>{
        timer.stop();
        timer.reset();
        console.log('Time has been stopped and reset.');
    }
`
Have any ideas why this is happening? If I had not have console logged the timer I would not have know that the timer is continuing because the time in the rendered text has stopped.

**Comment by albert-gonzalez** [comment]
Hi!

I see that you call the reset function. This function restarts the timer with its current config. Remove it and I think it should work!

Best regards.

**Comment by BakerShoeMaker** [comment]
Yes, that worked! Thanks!
