### ISSUE TITLE
Is there anyway to get the whole time in minutes?

### ISSUE THREAD

**Issue by vinyoliver** [albert-gonzalez/easytimer.js#7]
Hello,

For example, once I started a timer and I only need the minutes and seconds if get those values using timer.toString(['minutes', 'seconds'] for the first 59 minutes it's OK but once it has past the first hour the minutes starts again. Basically I wonder if there is anyway to get the time past only in minutes

Example when it' 1:30:00 I'd like to get 90:00 (only minutes and seconds)

**Comment by albert-gonzalez** [comment]
Hi!

you can't do this directly, but you can use both counters to do it:

`timer.getTotalTimeValues().minutes + ':' + timer.getTimeValues().seconds`

Best regards!

**Comment by vinyoliver** [comment]
Sorry for the late answear. That solved my problem, thanks!
