### ISSUE TITLE
Running on ESP32

### ISSUE THREAD

**Issue by SimonMerrett** [albert-gonzalez/easytimer.js#70]
Hi @albert-gonzalez I know this is not really an issue with your repo but I was hoping you could help me understand where I am going wrong implementing this on the ESP32. I'm saving all files (so far easytimer.min.js, easytimer.js, examples.css, examples.min.js) in a flat directory on the SPIFFS so the paths are very short. I realise that I probably don't need all those files - I initially thought that only easytimer.min.js was required but added the others out of desperation! The ESP32 is acting as a web server and serves the following html, which successfully displays the button and the 00:00:00 digits but nothing ever starts displaying the digits counting up. I am using Android Chrome to check results.
`<!DOCTYPE html>
<html>
 
    <head>
		<script  src="easytimer.min.js"></script>
		<script>
			function startTimer(){
					var timerInstance = new easytimer.Timer();
					var timer = new Timer();
					timer.start();
					timer.addEventListener('secondsUpdated', function (e) {
					$('#basicUsage').html(timer.getTimeValues().toString());
					});
			}
		</script>
    </head>
 
    <body>	

           <div id="basicUsage">00:00:00</div>
           <button onclick="startTimer()">Click me</button> 
	
    </body>

</html>`

I would be grateful if you can show where I'm making errors.

**Comment by albert-gonzalez** [comment]
Hi!

I see in your code that you are using jQuery, but it's not loaded. You have to add it in the head section.  If it does not work after adding jQuery, try to debug your code and see the execution error in the development console.

Best regards!

**Comment by albert-gonzalez** [comment]
I close this issue, if you have further questions, please ask!

**Comment by SimonMerrett** [comment]
Yes, that's fine. I tried with the jquery and couldn't find where it was going wrong in the console. Thanks for the advice before!
