### ISSUE TITLE
eventType 'secondsUpdated' executes every second?

### ISSUE THREAD

**Issue by BakerShoeMaker** [albert-gonzalez/easytimer.js#71]
I would like to decrement a number every second using the eventType 'secondsUpdated'. When I use the code below the item is not decremented.  Am I using this correctly?

 ```
timer.addEventListener('secondsUpdated', ()=>{
                  pb_totalSecondsNumber = 60;
                  pb_totalSecondsNumber--;
                  console.log(pb_totalSecondsNumber);
                  });
              });
```

**Comment by albert-gonzalez** [comment]
Hi!

the problem is that you are initializing pb_totalSecondsNumber every time in the secondsUpdated callback. Try something like this:

```js
let pb_totalSecondsNumber = 60;

timer.addEventListener('secondsUpdated', ()=>{
     pb_totalSecondsNumber--;
     console.log(pb_totalSecondsNumber);
 });
```

You can check out a running example here: https://runkit.com/albert-gonzalez/5cc9575ec01d42001ae5ea9f

Best regards!

**Comment by BakerShoeMaker** [comment]
Yes, that's it. thanks!
