### ISSUE TITLE
Hide the hours digits

### ISSUE THREAD

**Issue by heaversm** [albert-gonzalez/easytimer.js#72]
I only want to display the minutes in my countdown timer (trim off the initial 00: in a timer that currently reads 00:03:00). How do I do this? Also - is there a way to properly destroy / unmount the timer?

**Comment by albert-gonzalez** [comment]
Hi!

- You can use toString method, or get the values and format the output as you like. With toString method, run this: timer.getTimeValues().toString(['minutes', 'seconds'])

- You can't destroy the timer, but if you stop it and you don't use it anymore, the garbage collector will remove it from memory.

Best regards!

**Comment by x-ji** [comment]
Would be nice to document this in the "Getting Time Values" section of the documentation. It was not apparent how to format the output until I searched through Github issues. Thanks!
