### ISSUE TITLE
Enhance Typescript typings

### ISSUE THREAD

**Issue by IlCallo** [albert-gonzalez/easytimer.js#78]
Documentation states that `addEventListener` callback and `callback` property of `ITimerParams` have some parameters which are not annotated into the TS typings, this doesn't allow to use these listeners with Typescript.

Same for `on`, `off`, `removeEventListener`.

At the same time, `target` and `startValues` into `ITimerParams` are typed as `object` but they can be both typed as `Partial<TimeCounter> | [number|number|number|number|number]` making it more stricter.

Note that the tuple definition, written in that way, require exactly 5 elements.
If there are less or more, typescript will rightfully complain.

It's also a good idea to rename `Event` into something more package specific, because it clashes with native `Event` interface.

**Comment by albert-gonzalez** [comment]
Hi!

Thanks for your comments. I'll improve Typescript definitions asap.

**Comment by albert-gonzalez** [comment]
Hi!

I've just published v4.0.0 with the enhancements you commented. Can you review it, please?

https://github.com/albert-gonzalez/easytimer.js/blob/master/index.d.ts

Thanks!

**Comment by IlCallo** [comment]
Why is `event` parameter optional? Are there scenarios where it is not provided?

**Comment by albert-gonzalez** [comment]
Event is optional because you don't have to use it in the listener if you don't want to. But the event is always provided in the function.

I did not use the Partial because the validation was not very strict, and I preferred to make the interface explicit.

Thank you for your comments :)

**Comment by IlCallo** [comment]
All parameters are always optional for usage, in JS/TS 🤔

You can just do `timer.on('secondsUpdated', () => { /* something */ });` and you are good to go, the parameter is ignored.

Adding the question mark means "this parameter is not always defined, you have to check its type before usage", which is not what you want.

About `Partial`, it this case it would make the code more maintenable and avoid redundancy (doesn't affect usability, so no hard feelings about it by my part)

**Comment by albert-gonzalez** [comment]
Oops! I thought that the optional validation was for the callback declaration too, I am going to make a patch with this change then.

Thanks!

**Comment by albert-gonzalez** [comment]
Done! I have published v4.0.1. Now the parameters are required. I have tested it and works as expected.

Thanks again! If you don't have any more comments, please close the issue :).

**Comment by IlCallo** [comment]
Working as expected now, ty :)
