### ISSUE TITLE
Hola, no me importa la libreria mediante Script

### ISSUE THREAD

**Issue by mikiPP** [albert-gonzalez/easytimer.js#79]
Tal y como indicas,he añadido el script que dejas en tu página web  (https://albert-gonzalez.github.io/easytimer.js/#gettingTimeValuesExample)
pero,al intentar usarlo el fichero no es encontrado.
Exactamente,el error es: "Failed to load resource: net::ERR_FILE_NOT_FOUND"
con lo cual, no puedo usar la libreria. Me gustaría informarte debido a que no se si el error es mio 
o hay algún fallo. Muchas gracias de antemano.

el script en cuestión es:  <script src="lib/easytimer/dist/easytimer.min.js"></script>

**Comment by albert-gonzalez** [comment]
Hola!

La ruta que hay en la página es de ejemplo, para que te encuentre la librería debes escribir la ruta pública donde tengas la librería. Otra posibilidad es cargarla desde un CDN, por ejemplo: 

```html
<script src="https://cdn.jsdelivr.net/npm/easytimer.js@3.2.0/dist/easytimer.min.js"></script>
```

De esta forma no tienes que tenerla en tu servidor.

Saludos!

**Comment by mikiPP** [comment]
Hola!

Tenías razón (obviamente), ya me funciona.

Muchas gracias!

**Comment by mikiPP** [comment]
Y enhorabuena por tu trabajo!

**Comment by albert-gonzalez** [comment]
Me alegro de que ya funcione :).

Muchísimas gracias!!
