### ISSUE TITLE
Problem to countdown: 48h

### ISSUE THREAD

**Issue by sergiohpreis** [albert-gonzalez/easytimer.js#8]
Hello, 

How can I set the countdown with 48 hours ?

Regards,
Sergio

**Comment by albert-gonzalez** [comment]
Hi!

There was a bug detecting the target when the timer had to work with days. I fixed it and updated the library to the version 1.0.3.

This is an example using days: 
```js
var timer = new Timer();
timer.start({countdown: true, startValues: {hours: 48}});
timer.addEventListener('secondsUpdated', function (e) {
    $('#countdownExample .values').html(timer.getTimeValues().toString(['days', 'hours', 'minutes', 'seconds']));
});
```

I hope this solve your problem ;).
