### ISSUE TITLE
Should be able to config the Timer without starting it

### ISSUE THREAD

**Issue by voanhcuoc** [albert-gonzalez/easytimer.js#80]
I want to config the Timer without starting it.

**Expect API calls:**

```js
const timer = new easytimer.Timer(config);
// or
timer.configure(config);

function UICallback() {
  timer.start();
  // ...
  timer.pause();
}
```

**Actual workaround:**

```js
const timer = new easytimer.Timer();
timer.configured = false;

function UICallback() {
  if (timer.configured) {
    timer.start();
  } else {
    timer.start(config);
    timer.configured = true
  };
  // ...
  timer.pause();
}
```

Even if I can pass the same config every time I call `start()`, will it impact performance?

**Comment by albert-gonzalez** [comment]
Hi!

I think this change is not necessary. The start function is very simple and doesn't impact the performance, you can use the same configuration every time without any problem.

Best regards!
