### ISSUE TITLE
React-Native Undefined 'events'

### ISSUE THREAD

**Issue by albertosgr** [albert-gonzalez/easytimer.js#82]
Hi.

I'm using this library in with react-native and with the current release (4.0.1), I get compile error:

> error: bundling failed: Error: Unable to resolve module `events` from `<path>\node_modules\easytimer.js\dist\easytimer.js`: Module `events` does not exist in the Haste module map

If I install the events module, compile continues, but during run time app fails with error:

> "undefined is not an object (evaluating 'window.Event.prototype')"

Strangely if I debug the app remotely ("Debug JS Remotely") all seems to be working perfectly.

Can you assist on how to overcome this?

Thank you.

**Comment by albert-gonzalez** [comment]
Hi!

Sorry for the late response. I haven't used React-Native, but it seems that the library is incompatible with it. Easytimer uses CustomEvent and Event Emitter internally, maybe they are causing this issue. I'll try to fix this.

Best regards!

**Comment by AdamGerthel** [comment]
What a shame! Was just about to use this library in a React-Native project as well :(

**Comment by albert-gonzalez** [comment]
v4.3.0 is published, which uses a custom event emitter, so this issue should not happen anymore.

I close the issue :).
