### ISSUE TITLE
countdown using server time?

### ISSUE THREAD

**Issue by codyng** [albert-gonzalez/easytimer.js#84]
Hi author,

Is it possible to make the countdown using the server time?
What I think is that will the API support passing one more parameter used to indicate the current time (synchronised with the server) and then start the countdown?

It's because many users's local clock are several seconds delayed.

Thanks

**Comment by codyng** [comment]
The design of API interface is very good!

For the startValues (and target) parameters, instead of passing the specified days, hours, minutes, etc, is it possible to pass the single timestamp values as a high level usage. Thanks so much!

**Comment by albert-gonzalez** [comment]
Hi!

Sorry for the late response. I am sorry, it's not possible to synchronise the timer with a server. The timer uses the local machine clock to calculate the time and it's not prepared to use another system.

About the second question, you can pass only the seconds and the timer will transform them. For example:

`timer.start({startValues: { seconds: 1500 }})`

You can't pass the timestamp, but you can transform it to seconds before pass it to the timer.

Best regards
