### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by guilhermeagirardi** [albert-gonzalez/easytimer.js#85]
Hello!

I know it may seem like a dumb question, but I don't know much about Javascript.

I want to access the `task_id` variable as per the example below. But this code does not work for me. I know this has to do with context, but I don't know how to solve it.

```javascript
var task_id = '1sd58r';
var timer = new Timer();
timer.start();
timer.addEventListener('secondsUpdated', function (e) {
    $(`#task-${task_id}`).html(timer.getTimeValues().toString());
});
```

I want to have multiple timers for different tasks.

Thank you for your attention.

Best regards,

**Comment by albert-gonzalez** [comment]
Hi!

It seems correct, maybe there is some problem with the css selector. I wrote this little jsfiddle with your code, I hope it helps:

https://jsfiddle.net/q6z9vfkw/1/

Best Regards!
