### ISSUE TITLE
Can timer.addEventListener('secondsUpdated..... do other operations?

### ISSUE THREAD

**Issue by BakerShoeMaker** [albert-gonzalez/easytimer.js#87]
I'm trying to create a progress bar that will update every second and I put a function `this.changeProgressBarWidth();` inside the event listener that should be called every second in the code below. Is it possible because currently the function is not being called. FYI, I'm using React. 

` timer.addEventListener('secondsUpdated', ()=>{
          currentTime = timer.getTimeValues().toString(['minutes', 'seconds', ]);
           //This is not being called.
           this.changeProgressBarWidth();
           console.log("This is being called....................");
            });`

I have a progress bar component that needs to be updated like so:
`<ProgressBar
     now={this.state.progressBarStatusWidth}
     variant="success"
 />`

**Comment by albert-gonzalez** [comment]
Hi!

Yes, you can execute whatever you want in the addEventListener callback, make sure that you executed timer.start() and there are no errors in the log.  For example, you can do something like this:
```js
var timer = new Timer();
timer.addEventListener('secondsUpdated', () => {
    $('#basicUsage').html(timer.getTimeValues().toString());
});
timer.start();
```

**Comment by BakerShoeMaker** [comment]
Okay thanks!
