### ISSUE TITLE
Configure timer without starting

### ISSUE THREAD

**Issue by jsgv** [albert-gonzalez/easytimer.js#91]
I would like to create an additional suggestion to the timer initialization similar to the other issues created (#54, #80).

In my case I use several timers with all different configuration, and use the data from all of them.
I don't always use (start) them every timer, but I do use all the information from all of them.

Lets say that I have 3 different timers with the following configuration:

1. 5 minutes
2. 4 minutes
3. 3 minutes

My desired functionality:

```javascript
var timer1 = new Timer({
    startValues: {
        seconds: 300,
    },
});

// timer2, timer3 ...

var timers = [
    timer1,
    // timer2,
    // timer3
];

// I would like to be able to:
var fullTime = timers.reduce((sum, t) => t.getTimeValues().seconds + sum, 0); // 720 seconds

// Each timer knows its full time without starting it
// I can start each timer one by one as needed
timers[0].start();
timers[0].pause();

timers[1].start();
timers[1].pause();
```

Currently, there's no way of knowing the current state of each timer until after you start with the `config` options.

I suggest being able to initialize the Timer on object creation and ability to read the state of the timer without having to start/pause the clock.

I saw your suggestion for `start(config)/pause()`  and then `start()` to run the timer, but it seems like a race that might not always work as intended.

**Comment by albert-gonzalez** [comment]
Hi!

I think that I could move the initialization to the creation of the instance. I'll try to do it ASAP. Thanks for the suggestion!

Best regards!

**Comment by albert-gonzalez** [comment]
Hi!

I have just published v4.1.1 with this feature. Now you can pass a default config in the instance creation. If you pass other parameters to start function, these parameters will be merged with the default ones.

I hope it helps. If you can give me some feedback it would be perfect.

Best regards!

**Comment by jsgv** [comment]
Thanks! Appreciate your work on this project! :)

**Comment by albert-gonzalez** [comment]
I close this issue. If you need something more, please tell me!
