### ISSUE TITLE
Reset Countdown and Stop Timer

### ISSUE THREAD

**Issue by El-Than** [albert-gonzalez/easytimer.js#93]
Hi ! Thank you for you work ! It is possible to pause the timer when users press the reset button ?

**Comment by albert-gonzalez** [comment]
Hi!

You are welcome :). 

I am sorry, but the reset function always stops and starts again the timer. You can run the reset function and then the pause function to simulate that behaviour. For example:

```js
timer.reset();
timer.pause();
```

Best regards!

**Comment by El-Than** [comment]
I already tried this but when I click on reset, it only pauses the timer. I tried with callback and promises but it didn't work. For now I use a timeout but I loose 1 sec when I reset.

**Comment by albert-gonzalez** [comment]
Hi again!

I think you have to add the reset listener too. I have written this little jsfiddle, I hope it helps you: https://jsfiddle.net/9v0waLhr/

Best regards!
