### ISSUE TITLE
Reset without starting?

### ISSUE THREAD

**Issue by mmuurr** [albert-gonzalez/easytimer.js#95]
Hi, I'm wondering if there's a way to reset the timer (to the original values) _without_ starting the timer again?
For example, a countdown from 10 seconds to 0, then an action to reset to 10 but have the timer be in the paused state (so some connected div will show "10" again), then _later_ (on some event) start the countdown again.
Currently, this is the pattern:
```js
timer.start({countdown:true, startValues:{seconds: 10}});
// wait for the timer to stop at 0
// check to make sure it's in the stopped state: timer.isRunning() == false
timer.reset();  // this resets the values _and_ starts the timer again
```
Is this possible with easytimer?

**Comment by albert-gonzalez** [comment]
Hi!

reset function always restarts the timer. You can pause the timer again after resetting, or you can do something like that:

```js
const timer = new easytimer.Timer();
const timeElement = document.querySelector('.time');
let startValue;

timer.on('started', () => {
	startValue = timer.getTimeValues().toString();
});

timer.on('stopped', () => {
	timeElement.textContent = startValue;
});

timer.on('secondsUpdated', () => {
	timeElement.textContent = timer.getTimeValues().toString();
});

timer.start({countdown:true, startValues:{seconds: 10}});
``` 

I have done a jsfiddle with this code: https://jsfiddle.net/yL3tbec8/

I hope it helps.

Best regards!
