### ISSUE TITLE
Doc : last "HTML" Tab not displaying

### ISSUE THREAD

**Issue by igorrosenberg** [albert-gonzalez/easytimer.js#97]
**How to reproduce :**

- On https://albert-gonzalez.github.io/easytimer.js/
- Section "Default Parameters" / "Source code"
- Click on the HTML tab : it's not displaying.

**Comment by albert-gonzalez** [comment]
Hi!

Thanks for opening the issue. I'll fix it ASAP.

**Comment by albert-gonzalez** [comment]
Hi!

I've just fixed the tab. I close the issue :).

Best regards!
